theme: jekyll-theme-minimal
title: Yaolong Ju
description: 
  Ph.D. candidate from Schulich School of music, McGill University, Canada.
  Music and Tech enthusiastic
  Research interest: Machine learning, MIR, harmonic analysis
