theme: jekyll-theme-minimal
title: Yaolong Ju
description: 
  Ph.D. candidate from Schulich School of music, McGill University, Canada.
  Music and Tech enthusiastic.
  My research interests are machine learning, MIR, and harmonic analysis.
